//ORYGINALNY AUTOR: Mirosław Zelent, skrypt-cookies.pl, zmienione aby uzywac localstorage
function hovered(){document.getElementById("hcks").style.background="#969696"}
function unhovered(){document.getElementById("hcks").style.background="#d3d3d3"}
function hidecks(){document.getElementById("cookie").style.display="none";localStorage.setItem("cookieConsent",Date.now().toString())}
function shouldShowConsent(){const stored=localStorage.getItem("cookieConsent");if(!stored)return!0;const lastAccept=parseInt(stored,10);const weekInMs=7*24*60*60*1000;return(Date.now()-lastAccept)>weekInMs}
function skr_ckz(){if(!shouldShowConsent())return;let c=document.createElement("aside");let hc=document.createElement("span");c.setAttribute("id","cookie");c.style.zIndex=999999;hc.setAttribute("id","hcks");document.body.appendChild(c);c.style.background="#696969";c.style.color="#fafafa";hc.style.background="#d3d3d3";hc.style.color="#000000";c.innerHTML=`<span id="cinfo" style="flex: 1 1 auto; margin-top: 2px;">
    Używam ciasteczek, chrup chrup chruuup! [&nbsp;
    <a href="https://skrypt-cookies.pl/czym-sa-ciasteczka" target="_blank" style="text-decoration:underline;color:#fafafa;">
      Więcej informacji</a>&nbsp;]</span>`;hc.innerHTML="Okii";c.style.width="48%";c.style.minWidth="380px";c.style.maxWidth="90%";c.style.left="20px";c.style.bottom="20px";c.style.position="fixed";c.style.padding="20px";c.style.fontSize="17px";c.style.display="flex";hc.style.padding="12px 30px";hc.style.cursor="pointer";hc.style.display="flex";hc.style.borderRadius=".3rem";hc.style.alignItems="center";hc.style.marginLeft="15px";hc.addEventListener("click",hidecks,!1);hc.addEventListener("mouseenter",hovered,!1);hc.addEventListener("mouseleave",unhovered,!1);const sc=window.matchMedia("(max-width:575px)");if(sc.matches){c.style.width="auto";c.style.left="0";c.style.right="0";c.style.bottom="0";c.style.maxWidth="100%"}
c.appendChild(hc)}
if(window.addEventListener){window.addEventListener("load",skr_ckz)}else{window.attachEvent("onload",skr_ckz)}
window.onresize=function(){let c=document.getElementById("cookie");if(!c)return;const scr=window.matchMedia("(max-width:575px)");if(scr.matches){c.style.width="auto";c.style.left="0";c.style.right="0";c.style.bottom="0";c.style.maxWidth="100%"}else{c.style.width="48%";c.style.minWidth="380px";c.style.maxWidth="90%";c.style.left="20px";c.style.right="auto";c.style.bottom="20px"}};